### ISSUE TITLE
`workspace.addOpener` has incorrect signature and other complaints

### ISSUE THREAD

**Issue by lierdakil** [GlenCFL/atom-typings#7]
I thought about it for a few seconds and decided to create an issue here. So, here goes.

Opener functions get called like this: https://github.com/atom/atom/blob/v1.21.1/src/workspace.js#L1130

Which means that `addOpener` should have signature along the lines of

```ts
addOpener(opener: (uri: string, options?: OpenOptions) => ViewModel | undefined)
```

where `OpenOptions` are acutally these: https://github.com/GlenCFL/atom-typings/blob/0892f62c62a09543a9f645bc0e1115ef1b6df620/types/atom/index.d.ts#L5483-L5490
plus, in fact, anything else caller passes to `atom.workspace.open`, so it might make sense to make both of those generically-typed, e.g.

```ts
interface OpenOptions {
      initialLine?: number,
      initialColumn?: number,
      split?: "left"|"right"|"up"|"down",
      activatePane?: boolean,
      activateItem?: boolean,
      pending?: boolean,
      searchAllPanes?: boolean,
      location?: "left"|"right"|"bottom"|"center",
}
// ...
    open<O extends OpenOptions>(uri: string, options?: O): Promise<object>;
```

Also, are you sure that `HTMLElement` is accepted as a return value of `opener`? I have a suspicion that it's not, or that it needs `getTitle` at least (and then what's the difference with `{ getTitle() }`?)

For reference, `addOpener` is currently defined as https://github.com/GlenCFL/atom-typings/blob/0892f62c62a09543a9f645bc0e1115ef1b6df620/types/atom/index.d.ts#L5524

While on topic of `open`, actually, we can now pass views into `open` (see http://blog.atom.io/2017/05/23/docks-deep-dive.html#opening-items-in-docks), so the proper type would be something like this:

```ts
    open<V extends ViewModel = ViewModel, O extends OpenOptions>(uri: string | V, options?: O): Promise<V>;
```

Where `ViewModel` can be defined as 
```ts
interface ViewModel = { getTitle(): string }
```

Also, while I'm complaining, might as well complain a bit more. I'm not a big fan of the ongoing `object` infestation. For example, `Panel`s created with `add*Panel` have a concretely-typed item, and `getItem()` could be typed accordingly via generic. Just a thought.

**Comment by GlenCFL** [comment]
I'm not a fan of the object infestation either. I spent some time trying to define ```item``` a few weeks ago, but I wasn't happy enough with it to publish the result. The [View Registry Algorithm](https://github.com/atom/atom/blob/v1.21.0/src/view-registry.coffee#L93) would need to be defined in order to get rid of most of them. It's tricky for two reasons:

1. Each type of the union needs the correct signature. If that forces us to be too lax, then it's not much better than object itself.
2. Each usage of ```object``` would have to be reviewed, which would probably mean reading through or stepping through a lot of Atom code as we need to be sure that every single one uses that algorithm.

The return for the addOpener callback is based on behavior that I actually observed within a test package. The test involved returning an HTMLBodyElement from an opener that I had defined, which worked without any issues. An HTMLElement has a [title property](https://github.com/Microsoft/TypeScript/blob/faa04a2402288654fddf36f08e969492bea9ef7c/src/lib/dom.generated.d.ts#L4634), which I suspect is used if ```getTitle()``` isn't defined on the object. That still needs to be verified. The type of the return itself is probably just the union type that we'd define to represent the view registry algorithm.

Thanks for taking the time to investigate this. The other things you've mentioned will be fixed soon.

**Comment by GlenCFL** [comment]
The non-generic approach is being used for both until I review it further. With the interface, users can still modify this type using module augmentation. We run against the dtslint [no-unnecessary-generics](https://github.com/Microsoft/dtslint/blob/master/src/rules/noUnnecessaryGenericsRule.ts) rule when we do try to use the generics, so I need to ensure that the use of generics here is justified before trying to merge that into DT.

**Comment by lierdakil** [comment]
Well, wrt return type, here's a simple test (run in dev. console):

```js
div = document.createElement('div')
div.innerText = 'Hello, World!'
opener = (uri) => { if (uri == 'test://') return div }
atom.workspace.addOpener(opener)
atom.workspace.open('test://')
```

nets us
```
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
<embedded>:118178 Uncaught (in promise) TypeError: this.item.getTitle is not a function
    at TabView.module.exports.TabView.updateTitle (/home/livid/.local/share/atom/resources/app/node_modules/tabs/lib/tab-view.js:324:33)
    at new TabView (/home/livid/.local/share/atom/resources/app/node_modules/tabs/lib/tab-view.js:50:18)
    at TabBarView.module.exports.TabBarView.addTabForItem (/home/livid/.local/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:223:23)
    at /home/livid/.local/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:163:30
    at Function.module.exports.Emitter.simpleDispatch (/home/livid/.local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/home/livid/.local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.addItem (/home/livid/.local/share/atom/resources/app/src/pane.js:546:26)
    at Pane.module.exports.Pane.activateItem (/home/livid/.local/share/atom/resources/app/src/pane.js:489:20)
    at Workspace.<anonymous> (/home/livid/.local/share/atom/resources/app/src/workspace.js:1174:20)
    at Generator.next (<anonymous>)
    at step (/home/livid/.local/share/atom/resources/app/src/workspace.js:11:279)
```

Running the last line (`atom.workspace.open`) a *second* time actually does show the div, probably because something gets broken, but it doesn't work correctly, i.e. no tab is created for the div, it's just hanging in there. Having `title` attribute set doesn't change anything. Here are some screenshots:

Before running `atom.workspace.open('test://')`:
![image](https://user-images.githubusercontent.com/7275622/31895684-86537ca2-b81a-11e7-94d8-412466be64e4.png)
After:
![image](https://user-images.githubusercontent.com/7275622/31895733-9fc064de-b81a-11e7-9d0c-0458f5a96981.png)
For reference,
![image](https://user-images.githubusercontent.com/7275622/31895777-c2a25f34-b81a-11e7-99d7-befce2cfaa62.png)

Tested on Atom v1.21.1 (built from git source commit https://github.com/atom/atom/commit/2db900747f7dbac614f8d31a47487c40039016f2) on Linux.

**Comment by lierdakil** [comment]
As for `no-unnecessary-generics`, actually, yes, generics are pointless for `OpenOptions`. I was sleep-deprived and running exclusively on caffeine at the time of writing. Module/interface augmentation is the way to go here.

My comment on making `Panel` generic and making `add*Panel` functions generic in both arguments and return values still stands and shouldn't trigger `no-unnecessary-generics`, I believe.

**Comment by GlenCFL** [comment]
You're right about the HTMLElement being incorrect on ```addOpener```. I've changed the signature and added that ViewModel interface.

I've made Panel generic, as well as the add*Panel functions within Workspace. These definitely don't have the ViewModel constraint, with the [documentation](https://atom.io/docs/api/v1.21.1/Workspace#instance-addBottomPanel) indicating that it's the view registry algorithm.

**Comment by lierdakil** [comment]
> These definitely don't have the ViewModel constraint

I never suggested they do. Basically, `item` can be literally anything that could be used for `WeakMap` key, provided there's a handler registered for it in `ViewRegistry`, so no meaningful constraints apply. Well, besides `extends object` that is, you can't use strings or numbers as `item`s (or at least, even if someone could use some clever hack, I don't think that would be intended)

**Comment by GlenCFL** [comment]
Everything in this issue has been resolved within this repository, with the changes to DefinitelyTyped being in flight as well.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20900

Closing this, but feel free to open more issues or add additional comments to this one if you come across any additional errors or discover things which you simply dislike about the current definitions.
