### ISSUE TITLE
A couple missing methods

### ISSUE THREAD

**Issue by lierdakil** [GlenCFL/atom-typings#8]
Here are a couple missing methods in Atom typings I found:

```ts
  interface TextBuffer {
    destroy(): void
  }

  interface PackageManager {
    activatePackage(name: string): Promise<Package>
  }
```

None of these are documented, but all are used. Especially `PackageManager.activatePackage` -- it's widely used in specs. And you *have* to use `TextBuffer.destroy` on a buffer if it's created with `TextBuffer.load` directly.

**Comment by GlenCFL** [comment]
They tend to use the reference counting system for TextBuffer within Atom. I've added both it and `.destroy()`. There are also several functions used in conjunction with `activatePackage` within PackageManager, which I've added as well.

I don't mind adding important functionality like this to the definitions. You wouldn't even be able to start a [BufferedProcess](https://atom.io/docs/api/v1.21.1/BufferedProcess) if we went entirely by the API.

That original PR is still pending on DefinitelyTyped, so these changes are likely 7-10 days from being available there. The only way to speed that up is for there to be another owner for the definitions willing to review.
